[tools]
gcloud = "latest"
go = "1.25.0"
golangci-lint = "latest"
"npm:@google/clasp" = "latest"

[env]
_.file = ".env"

[tasks.fmt-md]
description = "lint and format markdowns"
run = "npx markdownlint-cli2 --fix **/*.md"

[tasks.dev]
description = "Run the local development server"
run = "go run ./cmd/local-server/"
dir = "go-bot"

[tasks.format]
description = "Format Go files using gofmt"
run = "gofmt -w ."
dir = "go-bot"

[tasks.lint]
description = "Lint Go files using golangci-lint"
run = "golangci-lint run"
dir = "go-bot"

[tasks.check]
description = "Run all formatters and linters for the Go project"
depends = ["format", "lint", "fmt-md"]

[tasks.register-commands]
description = "Register slash commands with Discord"
run = "go run ./cmd/register-commands/"
dir = "go-bot"

[tasks.deploy]
description = "Deploy the Go function to Google Cloud Functions"
run = '''
gcloud functions deploy reading-counter-dc \
  --gen2 \
  --runtime=go122 \
  --region=$GCP_REGION \
  --source=./go-bot \
  --entry-point=HandleInteraction \
  --trigger-http \
  --allow-unauthenticated \
  --set-env-vars=DISCORD_APP_PUBLIC_KEY=$DISCORD_APP_PUBLIC_KEY
'''
