[tools]
biome = "latest"
gcloud = "latest"
go = "1.25.0"
golangci-lint = "latest"
"npm:@google/clasp" = "latest"

[env]
_.file = ".env"

[tasks.fmt-md]
description = "lint and format markdowns"
run = "npx markdownlint-cli2 --fix **/*.md"

[tasks.fmt-go]
description = "Format Go files using gofmt"
run = "gofmt -w ."
dir = "go-bot"

[tasks.lint-go]
description = "Lint Go files using golangci-lint"
run = "golangci-lint run"
dir = "go-bot"

[tasks.fmt-js]
description = "Format JS files using Biome"
run = "biome format --write ."
dir = "gas-api"

[tasks.lint-js]
description = "Lint JS files using Biome"
run = "biome lint ."
dir = "gas-api"

[tasks.format]
description = "Run all formatters"
depends = ["fmt-go", "fmt-js", "fmt-md"]

[tasks.lint]
description = "Run all linters"
depends = ["lint-go", "lint-js"]

[tasks.check]
description = "Run all formatters and linters for the project"
depends = ["format", "lint"]

[tasks.register-commands]
description = "Register slash commands with Discord"
run = "go run ./cmd/register-commands/"
dir = "go-bot"

[tasks.deploy]
description = "Deploy the Go function to Google Cloud Functions"
run = '''
gcloud functions deploy reading-counter-dc \
  --gen2 \
  --runtime=go122 \
  --region=$GCP_REGION \
  --source=./go-bot \
  --entry-point=HandleInteraction \
  --trigger-http \
  --allow-unauthenticated \
  --set-env-vars=DISCORD_APP_PUBLIC_KEY=$DISCORD_APP_PUBLIC_KEY
'''
